from __future__ import annotations

from typing import Protocol


class Transport(Protocol):
    def publish(self, channel: str, message: bytes) -> None: ...

    def consume(self, channel: str, timeout: int = 5) -> bytes | None: ...

    def ack(self, receipt: str) -> None: ...

    def nack(self, receipt: str, *, requeue: bool = True) -> None: ...


class OutboxStore(Protocol):
    def add(self, message: bytes) -> str: ...

    def claim(self, limit: int = 100) -> list[bytes]: ...

    def complete(self, receipt: str) -> None: ...


class InboxStore(Protocol):
    def seen(self, message_id: str) -> bool: ...

    def record(self, message_id: str) -> None: ...
